apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-redis
  labels:
    app: ocr-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocr-redis
  template:
    metadata:
      labels:
        app: ocr-redis
    spec:
      nodeSelector:
        app: redis-store
      tolerations:
        - key: "sku"
          operator: "Equal"
          value: "redis"
          effect: "NoSchedule"
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "1"
              memory: "4Gi"
            limits:
              cpu: "2"
              memory: "8Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: ocr-redis-service
spec:
  selector:
    app: ocr-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
